Style/Lambda:
  Exclude:
    - 'app/models/dialogue.rb'

Lint/LiteralAsCondition:
  Exclude:
  - 'app/controllers/dialogues_controller.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/models/message_spec.rb'