name: "Ruby on Rails CI"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: chat_test
          POSTGRES_HOST_AUTH_METHOD: trust
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:@postgres:5432/chat_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Set up database schema
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run RuboCop
        run: bundle exec rubocop
