name: "Ruby on Rails CI"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PORT: 5432
          POSTGRES_HOST: postgres
          POSTGRES_DB: chat_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:@localhost:5432/chat_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database schema
        run:
          bin/rails db:create
          bin/rails db:setup

      - name: Run RSpec tests
        run: bundle exec rspec spec

      - name: Run RuboCop
        run: bundle exec rubocop
